# Generated by Django 5.2.1 on 2025-08-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_did_hash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.CharField(editable=False, max_length=128, unique=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('block_confirmations', models.PositiveIntegerField(blank=True, null=True)),
                ('block_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.position')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-timestamp'],
                'unique_together': {('voter_did_hash', 'position')},
            },
        ),
    ]
