# Generated by Django 5.2.1 on 2025-08-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
