# Generated by Django 5.2.1 on 2025-08-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_vote_is_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='block_confirmations',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='block_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='block_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
