# Generated by Django 5.2.1 on 2025-08-26 12:42

import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import elections.directories
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('ended', 'Ended'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_synced', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections', to='accounts.department')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections', to='accounts.school')),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='short position description', null=True)),
                ('eligible_levels', models.JSONField(default=list, help_text='List of eligible levels, e.g., [1, 2, 3]')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], default='A', help_text='Specify gender eligibility for this position.', max_length=1)),
                ('is_synced', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='elections.election')),
                ('eligible_departments', models.ManyToManyField(blank=True, to='accounts.department')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['election', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('bio', ckeditor.fields.RichTextField(blank=True, help_text='Candidate short biography', null=True)),
                ('manifesto', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Candidate manifesto with formatting & media')),
                ('image', models.ImageField(blank=True, null=True, upload_to=elections.directories.candidate_directory)),
                ('campaign_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for campaign', max_length=255)),
                ('is_synced', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.position')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['position'],
                'unique_together': {('position', 'student')},
            },
        ),
    ]
