# Generated by Django 5.2.1 on 2025-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_candidate_is_synced_position_is_synced"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="is_synced",
            field=models.BooleanField(default=False),
        ),
    ]
