# Generated by Django 5.2.1 on 2025-06-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_department_user_department'),
        ('elections', '0002_election_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='eligible_departments',
            field=models.ManyToManyField(blank=True, to='accounts.department'),
        ),
    ]
