# Generated by Django 5.2.1 on 2025-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_election_is_synced"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="election",
            name="is_synced",
        ),
        migrations.AddField(
            model_name="candidate",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="position",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
