# Generated by Django 5.2.1 on 2025-08-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_remove_election_is_synced_candidate_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
