# Generated by Django 5.2.1 on 2025-08-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_election_is_cancelled_election_is_suspended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='election',
            name='is_suspended',
        ),
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('ended', 'Ended'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
