# Generated by Django 5.2.1 on 2025-08-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_remove_election_is_cancelled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='last_synced_at',
            new_name='last_synced',
        ),
        migrations.AddField(
            model_name='candidate',
            name='campaign_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for campaign', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/images/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='promise',
            field=models.TextField(blank=True, help_text='Main campaign promise or slogan'),
        ),
    ]
