# Generated by Django 5.2.1 on 2025-08-10 10:25

import elections.directories
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_rename_last_synced_at_candidate_last_synced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=elections.directories.candidate_directory),
        ),
    ]
