# Generated by Django 5.2.1 on 2025-08-12 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_department_school'),
        ('elections', '0009_candidate_created_at_position_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='election',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections', to='accounts.department'),
        ),
    ]
