# Generated by Django 5.2.1 on 2025-08-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_election_school_alter_election_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
