# Generated by Django 5.2.1 on 2025-08-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_alter_candidate_code_alter_election_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
