# Generated by Django 5.2.1 on 2025-08-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0012_election_is_synced_election_last_synced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='last_synced_at',
            new_name='last_synced',
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], default='A', help_text='Specify gender eligibility for this candidate.', max_length=1),
        ),
        migrations.AddField(
            model_name='position',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], default='A', help_text='Specify gender eligibility for this position.', max_length=1),
        ),
        migrations.AlterField(
            model_name='position',
            name='eligible_levels',
            field=models.JSONField(default=list, help_text='List of eligible levels, e.g., [1, 2, 3]'),
        ),
    ]
