# Generated by Django 5.2.1 on 2025-08-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0013_rename_last_synced_at_position_last_synced_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='gender',
        ),
    ]
