# Generated by Django 5.2.1 on 2025-08-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_remove_candidate_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_synced',
        ),
        migrations.RemoveField(
            model_name='election',
            name='last_synced',
        ),
    ]
