# Generated by Django 5.2.1 on 2025-08-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_remove_election_is_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
