# Generated by Django 5.2.1 on 2025-08-23 17:35

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0016_election_is_synced_election_last_synced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='promise',
        ),
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Candidate short biography', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='manifesto',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Candidate manifesto with formatting & media'),
        ),
        migrations.AlterField(
            model_name='election',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
