# Generated by Django 5.2.1 on 2025-08-24 00:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0017_remove_candidate_promise_candidate_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='short position description', null=True),
        ),
    ]
