# Generated by Django 5.2.1 on 2025-05-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='index_number',
            field=models.CharField(default='UEB3502721', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_enrolled',
            field=models.IntegerField(default=2025),
        ),
    ]
