# Generated by Django 5.2.1 on 2025-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_index_number_user_year_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='index_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
