# Generated by Django 5.2.1 on 2025-06-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_index_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 100'), (2, 'Level 200'), (3, 'Level 300'), (4, 'Level 400')], null=True),
        ),
    ]
