# Generated by Django 5.2.1 on 2025-06-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='did',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, unique=True),
        ),
    ]
